kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "pipeline { \nagent any\n stages { stage('Build'){ steps{ slackSend \"Job Started - (<${BUILD_URL}|Open>)\" } } } }"